### ISSUE TITLE
Feature: ECCU wildcard clearing

### ISSUE THREAD

**Issue by cdenneen** [mikamai/akamai_api#22]
So ECCU now supports wildcard clearing where as the CCU doesn't (has to be full path).
Can this gem be updated to support wildcard remove/invalidate for ECCU function?

**Comment by shark-src** [comment]
+1 for this.  Having this feature would unblock one of my projects to move away from the http wrapper for ccu api requests.

**Comment by spaghetticode** [comment]
FYI, from the akamai docs: 
«Using ECCU applications, Akamai recommends that you limit the number of
matches to 250 or fewer—see “ECCU Matches and the purge.data File” on page 6
for a definition of ECCU matches. Submitting more than 250 invalidation requests
at one time can result in a “global invalidation” –revalidating all content for that host
header»
I think this should be added in the readme once the feature is added.

**Comment by nicolaracco** [comment]
Feature implemented as 'akamai_api eccu revalidate' command and gem released with version 0.4.0. Can you check if it is ok ?

**Comment by nicolaracco** [comment]
@cdenneen @shark-src I'm closing this. Let me know if you have other suggestions
